wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.3
      5: 0.10.30
      8:
      - 5
batch_size:
  desc: null
  value: 10
client_num_per_round:
  desc: null
  value: 2
clip:
  desc: null
  value: 0.5
comm_round:
  desc: null
  value: 200
data_dir:
  desc: null
  value: '"./../../../data/mnist"'
dataset:
  desc: null
  value: mnist
epochs:
  desc: null
  value: 10
frequency_of_the_test:
  desc: null
  value: 1
is_mobile:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.03
model:
  desc: null
  value: lr
partition_alpha:
  desc: null
  value: 0.5
partition_method:
  desc: null
  value: hetero
wd:
  desc: null
  value: 0.001
